### ISSUE TITLE
how to output golang map in template in source order?

### ISSUE THREAD

**Issue by dabba39** [flosch/pongo2#100]
following snippet from a template:

``` html
<ul class="nav nav-tabs">
     {% for route in routes_order %}
        <li role="presentation" {% if route == current_route %}class="active"{% endif %}>
            <a title="{{ routes.route }}" href="{{ route }}">{{ routes.route }}</a>
        </li>
     {% endfor %}
 </ul>
```

doesn't work, because routes.route is a routes["route"]. How to make that dynamical? 
##

**Comment by dabba39** [comment]
data supplied looks like following:
```go
map[string]interface{}{"current_route": "fo",
"routes": map[string]string{"foo": "bar", "fo": "bar"}, "routes_order": []string{"fo", "foo"}}
```

**Comment by flosch** [comment]
Maps don't have a specific order, so there's no way to output in "source order". However, you can output all keys and values like this:

   {% for key, value in myMap %}
      {{ key }} -> {{ value }}
   {% endfor %}

**Comment by flosch** [comment]
You could develop a filter which takes your key (from your routes_order) as an argument and returns the specific map value.
