### ISSUE TITLE
Using templates with virtual file system

### ISSUE THREAD

**Issue by sharpner** [flosch/pongo2#105]
hi there!

I am currently trying to use pongo2.v3 in combination with [https://github.com/jteeuwen/go-bindata](go-bindata) but I am not sure on how to register files on a TemplateSet.

I am currently trying to define a custom set 
```assetSet := pongo2.NewSet("assetfs")```

Now there is no clear way on how to register filenames and data to the TemplateSet. I tried using Globals but that seems to be for variables only...

Any hint? I couldn't find any documentation so I read your code and I am now not even sure that this is possible.

I even tried using fromCache, but I couldn't find a way to warmup the cache either. 

Maybe you can help me out, thx :-)

**Comment by flosch** [comment]
You can call the `From*` functions on template sets, e. g. `FromString`. You could simply convert and pass your asset's []byte to this function.

Another way would be (only available in the `master` branch) to use the `TemplateLoader` interface in conjunction with the `NewSet` function. This would allow you to implement a virtual filesystem for go-binddata.

**Comment by sharpner** [comment]
ah the second solution sounds promising. 

The first one won't work because "includes" and "extends" will still access the filesystem, right?

**Comment by flosch** [comment]
Correct!

**Comment by sharpner** [comment]
I had a quick look at the TemplateLoader interface, will report if it works :-) Thanks for the support so far!

**Comment by flosch** [comment]
Looking forward to your feedback. You're welcome.

**Comment by sharpner** [comment]
So it works :D Awesome! 
I just find the Abs method confusing. I currently got a hacky implementation of it to work:

```go
func (m memoryTemplateLoader) Abs(base, name string) string {
  if !filepath.IsAbs(name) {
    if !strings.HasPrefix(name, "templates") {
      //TODO don't hardcode this prefix
      return "templates/sites/" + name

    }
    return name
  }

  return base
}
```
Could you explain a little bit more how the extended behaviour of the ```Abs``` is?

Maybe it could be simplified somewhat?

**Comment by sharpner** [comment]
it's on github now, https://github.com/sharpner/pobin I will resolve the todo today hopefully.

**Comment by sharpner** [comment]
Well but at least my issue is resolved, thanks for the quick help
