### ISSUE TITLE
Parsing multiple template at once?

### ISSUE THREAD

**Issue by digitalcraftsman** [flosch/pongo2#109]
Is it possible to parse an entire folder of templates á la `template.ParseGlob("views/*")` with the `html/template` package?

Obviosly, `template.ParseGlob()` can't be used in combination with `pongo2.Must()`, since a `*pongo2.Template` is required.

**Comment by flosch** [comment]
You can walk a directory using `filepath.Glob` and create list or map of `pongo2.Template` instances. Does this answer your question?

**Comment by digitalcraftsman** [comment]
What's the best way to create new instances of `*pongo2.Template`? A template is a struct with private fields only and a constructor isn't available.

**Comment by flosch** [comment]
The `From*` functions are returning `Template` instances. You're welcome.
