### ISSUE TITLE
The product lacks the normal documentation about template syntax

### ISSUE THREAD

**Issue by monoflash** [flosch/pongo2#114]
This library can not be used because the documentation is not. Documentation about template syntax. And that's too bad.

Pongo2 wanted to use, but the time to start writing the template takes more than required.
The library is intended only for those who know python and django, for everyone else pongo2 is useless.

**Comment by chespinoza** [comment]
+1

**Comment by flosch** [comment]
pongo2 is developed as a Go-pendant for Django templates. If you want to learn that type of template language, Django provides good docs. Caveeats and compatibility issues are mentioned in the README. Please have a look there for a link to Django's documentation.
