### ISSUE TITLE
"split" functionality?

### ISSUE THREAD

**Issue by wrouesnel** [flosch/pongo2#122]
Just in case I'm missing something before I go off an implement a filter for it, is there currently no way to achieve the jinja2 equivalent of some_arg.split("\n") ? Basically I want to get an array of lines out of variable.

**Comment by flosch** [comment]
Hey,

no, there's not such a thing. But it's easy to just pass your own splitting function to pongo2's context, for example:

```
        tpl, err := pongo2.FromString(`Hey {{ split(s, ",")|join:"-" }}`)
        if err != nil {
                panic(err)
        }
        out, err := tpl.Execute(pongo2.Context{
                "split": strings.Split,
                "s": `this,is,cool`,
        })
        if err != nil {
                panic(err)
        }
        fmt.Println(out)
```
