### ISSUE TITLE
url_for in pongo2

### ISSUE THREAD

**Issue by massoudAfrashteh** [flosch/pongo2#125]
Hello 
In Jinja2 there's a function with url_for name which returns a route func url in template files. It's very usefull in Jinja2 can you add it to Pango2?

Thank you
##

**Comment by Machiel** [comment]
Sounds to me like this is not for pongo2 to implement. pongo2 is totally router independent so wouldn't know anything about your routes.

This is probably best solved by implementing this yourself.
