### ISSUE TITLE
Escaping replaced HTML by default

### ISSUE THREAD

**Issue by shardnit** [flosch/pongo2#129]
While testing pongo2 for inserting HTML elements in a template, I see that HTML tags are escaped by default. Is there any way to turn off this behaviour?

Sample program:

```go
package main

import (
	"fmt"

	"gopkg.in/flosch/pongo2.v3"
)

func main() {
	tpl, err := pongo2.FromString("Hello {{ name }}!")
	if err != nil {
		panic(err)
	}
	// Now you can render the template with the given
	// pongo2.Context how often you want to.
	out, err := tpl.Execute(pongo2.Context{"name": "<p> florian </p>"})
	if err != nil {
		panic(err)
	}
	fmt.Println(out)
}
```

And the output is `Hello &lt;p&gt; florian &lt;/p&gt;!` instead of `Hello <p> florian </p>!`

**Comment by gavbaa** [comment]
You're looking for the autoescape tag:

```
{% autoescape on %}
    {{ body }}
{% endautoescape %}
```

You can read more about it here: https://docs.djangoproject.com/en/1.9/ref/templates/builtins/#autoescape

**Comment by shardnit** [comment]
👍
