### ISSUE TITLE
Struct render form like django as_table()?

### ISSUE THREAD

**Issue by yansuan** [flosch/pongo2#130]
https://docs.djangoproject.com/en/1.9/ref/forms/api/#as-table
##

**Comment by gavbaa** [comment]
Pongo isn't really the place for this, as it's only a template language.  You would need to combine Pongo with something like https://github.com/bluele/gforms, which is a forms processing and rendering library, to do what you want.

**Comment by yansuan** [comment]
OK, thank you, and want to join this feature.
