### ISSUE TITLE
Set behaviour for invalid variable

### ISSUE THREAD

**Issue by bclermont** [flosch/pongo2#131]
https://docs.djangoproject.com/en/1.7/ref/templates/api/#how-invalid-variables-are-handled

is there a way to `panic` or at least change default behaviour when a variable isn't available?
##

**Comment by flosch** [comment]
You can do something like 

```
{% if myVar %}Var exists{% else %}Var doesn't exist{% endif %}
```

or 

```{{ myVar|default:"no value" }}```

**Comment by bclermont** [comment]
Yes, I know... but it was just to have a default behaviour and force all the template editors that work on a project to always fix their variable names instead of wait until it's empty and end-user report error.

a little bit like if I render the following bash script template :

```
rm -rf /{{ Root_Directory }}
```

instead of `RootDirectory`

that will wipe `/` instead of return an error :)

**Comment by flosch** [comment]
You the default-filter instead :)
