### ISSUE TITLE
{{ block.Super }} bug report

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [flosch/pongo2#133]
just see codes

included.html

```
{% block content %}
    testData
{% endblock %}
```

base.html

```
{% include "included.html" %}
```

extend1.html

```
{% extends "included.html" %}

{% block content %}
    {{ block.Super }}

    <div>
        my content
    </div>
{% endblock %}
```

extend2.html

```
{% extends "base.html" %}

{% block content %}
    {{ block.Super }}

    <div>
        my content
    </div>
{% endblock %}
```

the extension div of extend2.html could not show, extend1.html works fine.
It seems to be the base template can not include another template.
Is it a bug?

and can {{block.Super}} change to {{block.super}} just the same as django?
##

**Comment by robvdl** [comment]
I think the reason it's called Super instead of super, because it's an exported function in Go, check the commit just merged.

**Comment by ziyouchutuwenwu** [comment]
i think you are right,  but is the other question really a bug?

**Comment by BoredTape** [comment]
i find this problem too

**Comment by fermin-silva** [comment]
Is there any update on this?
Is the project abandoned?

Thanks

**Comment by flosch** [comment]
No update yet, it's not abandoned either. I just had no time to fix it :)

**Comment by fermin-silva** [comment]
Nevermind, in my case it's because i was using the v3 branch, which doesn't have block.Super support.
Any plan to backport it to v3, as it's still the current stable branch ?

Thanks

**Comment by flosch** [comment]
v4.0.0 is out now, so feel free to use it.
