### ISSUE TITLE
Recursive includes.

### ISSUE THREAD

**Issue by nsf** [flosch/pongo2#134]
Shouldn't pongo2 protect from recursive includes by default?

Something like in template.tpl:

```
Hello, {% include "template.tpl" %}
```
##

**Comment by gavbaa** [comment]
Recursive includes can be inside if tests, and should be totally allowed.  You can do clever things like build tree structures with recursive includes.

**Comment by flosch** [comment]
I agree with @gavbaa.

**Comment by DavidSvetlik** [comment]
Closed ticket without any explanation, awesome.
