### ISSUE TITLE
call struct method , but not working

### ISSUE THREAD

**Issue by moofeng** [flosch/pongo2#145]
package main

import (
    "github.com/flosch/pongo2"
)

func main() {
    ctx := map[string]interface{}{
        "Test": Test{Name: "My Test"},
    }

```
tpl, _ := pongo2.FromString("{{ Test.ShowName() }}")

out, _ := tpl.Execute(ctx)

tpl, _ = pongo2.FromString("{{ Test.Name }}")

out, _ = tpl.Execute(ctx)

println(out)
```

}

type Test struct {
    Name string
}

func (t *Test) ShowName() string {
    return "ShowName"
}

output

```
$ go run main.go
My Test 

```

**Comment by lessmd** [comment]
thanks
[https://github.com/flosch/pongo2/issues/8](url)
