### ISSUE TITLE
How to use the "for" tag to iterate the number

### ISSUE THREAD

**Issue by Maksadbek** [flosch/pongo2#148]
For example I want to create a simple for loop from 0 to 10:
```
for  i in range(10) {
...
}
```

How this can be done ?

The following is not giving the expected result:
```
{% for i in range(100) %}
    {{ i }}
{% endfor %}
```

**Comment by gavbaa** [comment]
The Django template language that this is built on doesn't offer that as a built-in: https://code.djangoproject.com/ticket/5172 .  This could be added as a custom tag separately within your own project.

**Comment by Maksadbek** [comment]
@gavbaa Thanks
