### ISSUE TITLE
Pongo2 template file extension

### ISSUE THREAD

**Issue by rafamds** [flosch/pongo2#149]
Hello,
first let me thank you for the package 😄 . 

Currently to support code highlighting on VS Code I use `.dj.html` extension on the template files. I wanted to use a more intuitive extension, like `.p2` for example. Have you thought on a common extension to use? I will develop a VSCode extension to recognise that and enable code highlight.

Cheers.

**Comment by bosenok** [comment]
I use simple `.html`

**Comment by darol100** [comment]
@bosenok `.html` works for 95% of the time. However, it will be nice to have a plugin where it can help if something is wrong with your template logic.

**Comment by flosch** [comment]
I agree. Just use .html. 👍
