### ISSUE TITLE
Underscore variable names.

### ISSUE THREAD

**Issue by wmaness** [flosch/pongo2#151]
I have structs from an external source in the form of
image.crops.4_3

Pongo2 doesn't seem to allow the underscore as part of the variable name, even though it is present in the struct, ie.
`{% for key, value in image.crops %}
    {{key}}: {{value}}
{% endfor %}`
yields
4_3: http//whatevermyurlis

but image.crops.4_3 fails in compilation with:

2017/02/07 13:54:48 stderr: panic: [Error (where: parser) in [...] | Line 45 Col 66 near '_3'] '}}' expected

Any thoughts?

**Comment by gavbaa** [comment]
To add to this ticket, I can confirm that in Django, that would be a valid usage of a map/dictionary.  Roughly the following in a Django app:

```
    context = {
        'dd': {
            'a': 'hi',
            '4_3': 'nope',
        },
    }
    return HttpResponse(template.render(context, request))
```

And a template like this:

```
::{{ dd.a }}::<br>
::{{ dd.4_3 }}::<br>
```

Produces valid output:

```
::hi::
::nope::
```

So if the goal is to match Django's capabilities, this seems reasonable to fix.

For now, the work around is to use a template tag for arbitrary key dictionary lookup.  You can do it in a way similar to what's described in this SO post: http://stackoverflow.com/questions/12852862/accessing-dictionary-keys-with-invalid-identifiers-in-django-templates .

**Comment by wmaness** [comment]
Addendum: This seems to be a limited case  foo_bar parses fine  4_3 as a key does not.

**Comment by gavbaa** [comment]
It's most likely because a variable starting with a number is being treated as an array index.  It might not be sensitive to the fact that the particular data structure is a map and that's allowed for a map.  The Django rules for this are stated here: https://docs.djangoproject.com/en/1.10/ref/templates/api/#variables-and-lookups

```Variable names must consist of any letter (A-Z), any digit (0-9), an underscore (but they must not start with an underscore) or a dot.```

**Comment by flosch** [comment]
Fixed.
