### ISSUE TITLE
How to get better template errors?

### ISSUE THREAD

**Issue by Siredwin** [flosch/pongo2#152]
How do i make sure to get more informative template errors instead of "internal server error"? It is really taking my time combing through html.

Is there a TEMPLATE_DEBUG setting somewhere?

**Comment by flosch** [comment]
Can you provide some code on how you're rendering the template?

**Comment by Siredwin** [comment]
I am using this example by Machiel -- https://machiel.me/post/pongo2-with-echo-or-net-http/

    package main

import (
	"errors"
	"io"
	"net/http"

	"github.com/labstack/echo"
	"github.com/flosch/pongo2"
)

type Renderer struct {
	Debug bool
}

func (r Renderer) Render(w io.Writer, name string, data interface{}, c echo.Context) error {

	var ctx pongo2.Context

	if data != nil {
		var ok bool
		ctx, ok = data.(pongo2.Context)

		if !ok {
			return errors.New("no pongo2.Context data was passed...")
		}
	}

	var t *pongo2.Template
	var err error

	if r.Debug {
		t, err = pongo2.FromFile(name)
	} else {
		t, err = pongo2.FromCache(name)
	}

	// Add some static values
	ctx["version_number"] = "v0.0.1-beta"

	if err != nil {
		return err
	}

	return t.ExecuteWriter(ctx, w)
}

func main() {
	renderer := Renderer{
		Debug: false,
	}

	e := echo.New()
	e.Renderer = renderer
	e.GET("/", Index)
	e.Start(":1313")
}

func Index(c echo.Context) error {
	data := pongo2.Context{
		"name": "Machiel",
		"answer": func() int {
			return 42
		},
		"items": []string{
			"Apple", "Pear", "Banana", "Pineapple",
		},
	}

	return c.Render(http.StatusOK, "index.html", data)
}``

**Comment by flosch** [comment]
Check the errors returned by `pongo2.FromFile/FromCache` and `ExecuteWriter`. This should give you a hint when there's some error in your template.

**Comment by Siredwin** [comment]
Never mind, i do get template errors after all. It was echo errors causing the problem.
