### ISSUE TITLE
Spaceless not working

### ISSUE THREAD

**Issue by DavidSvetlik** [flosch/pongo2#155]
Hi,

it seems that [spaceless](https://docs.djangoproject.com/en/dev/ref/templates/builtins/?from=olddocs#spaceless) tag is not working in pongo2. Trying that in you demo environment and does nothing https://www.florian-schlachter.de/pongo2/ .

Thank you.

**Comment by gavbaa** [comment]
Can you provide a reproduction example?  I did a few tests on this just last week, and it appears to be working as defined in the Django docs.  For instance, if you start with:

`
{% spaceless %}
<body>
<div>   adsfadsf    <a>
    Welcome to 
    pongo2 {{ pongo2.version }}! :-)
</a>  </div>
        </body>
{% endspaceless %}
`

You end with:

`
<body><div>   adsfadsf    <a>
    Welcome to 
    pongo2 dev! :-)
</a></div></body>
`

Which is correct per the definition of the spaceless tag in the Django docs.  Text between tags preserves spaces, only touching tags do not.

**Comment by DavidSvetlik** [comment]
Oh, I tried it on specific case when I have multiple variable declarations like

```
{% spaceless %}
{% set a = "1" %}
{% set a = "2" %}
{% set a = "3" %}
{% endspaceless %}
```

And thought it will remove all line breaks. If it's not supposed to work like that, is there some workaround? I want to clear all line breaks before doctype.

**Comment by DavidSvetlik** [comment]
@gavbaa Thank you. Sorry for invalid report.

**Comment by gavbaa** [comment]
Consider contributing it to the pongo2-addons project! :)
