### ISSUE TITLE
example of "in"?

### ISSUE THREAD

**Issue by iandouglas** [flosch/pongo2#157]
Thanks for a great library, it's really simplified our port from Python to Go.

We do have a use case that doesn't seem to work, and I'm curious if there's a workaround:

`{% if my_string in ["abc", "def", "ghi", "jkl"] %}`

We get an error of:

`[Error (where: parser) in <string> | Line 1 Col 19 near '["abc", "def", "ghi", "jkl"] %}'] Expected either a number, string, keyword or identifier.`

Trying it on the playground says that `[` is an unknown character. Do you happen to know of a workaround?
![screen shot 2017-04-03 at 5 05 41 pm](https://cloud.githubusercontent.com/assets/168030/24635299/dc825f6a-188f-11e7-81b6-a4a01a352e78.png)

**Comment by gavbaa** [comment]
The error message is correct, unfortunately.  In Go you can't have an untyped array like that, it would have to be specified as []string{"abc", "def"}, and that's not valid in the template syntax.  If you need to declare that level of static variable, you need to add it as a variable to the context.

**Comment by iandouglas** [comment]
Super, thanks. What about "is defined"?
`{% if my_contaxt_string is defined %}`

**Comment by gavbaa** [comment]
The Django template language (and by extension Pongo) doesn't have any concept of is defined on the context.  It's a core tenet, you can read more here: https://docs.djangoproject.com/en/1.10/ref/templates/api/#invalid-template-variables .  There's no way to do this without a custom tag that digs into the Context itself (via the ExecutionContext).

**Comment by iandouglas** [comment]
awesome, thanks!
