### ISSUE TITLE
math in parentheses not supported?

### ISSUE THREAD

**Issue by iandouglas** [flosch/pongo2#158]
I'm trying to do something like {{ (16/2)|integer }} and I'm getting an error on the filter pipe. Is this kind of operation not supported? (I couldn't see any test cases that support it)

`[Error (where: parser) in <string> | Line 1 Col 113 near '|'] '}}' expected`

Without the parentheses, {{ 57/15|integer }} seems to work alright but some existing formats we have include these parens around our math and I'm trying to figure out if we should regex out the parens.

**Comment by gavbaa** [comment]
If we go by the rules of Django templates, division isn't allowed at all in templates.

`{{ 16/2 }}` gives a 500 with

```TemplateSyntaxError at /polls/
Could not parse the remainder: '/2' from '16/2'```

While some mathematical operations in Pongo do technically work, since it's expanded behavior from what Django supports, edge cases surrounding more involved expressions might be the straw that breaks the camel's back. :)

**Comment by gavbaa** [comment]
I connected the dots in your last few requests; you're coming from Jinja, aren't you?

Personally, I'd love for this library to move closer to Jinja syntactically, and am completely open to supporting efforts to that regard (in a fork?  New project?  flosch would have to weigh in).  But, right now the stated goal is to target Django templates.

**Comment by iandouglas** [comment]
You got me. :) We're using Django for our old API, which we're porting to Go obviously, but with Jinja templates.

I've worked through several other things like time.strftime() calls, and Jinja also has an `|int` filter which I'm doing some regex to turn into `|integer` and so on. Good times.

Thanks for your effort on this library, it's saved us a ton of time!
