### ISSUE TITLE
Filter to get dict's value by key name

### ISSUE THREAD

**Issue by shashankmehra** [flosch/pongo2#162]
Something like `{{ dict|key:key_name }}`. So if you have a `map[string]interface{}` you can fetch values using a key stored in some other variable.

Although Django developers are [refusing](https://code.djangoproject.com/ticket/3371) to add a filter to perform this simple task (even Go templates can do this) there is no reason why pongo2 needs to follow suit, unless you really want to stick with their template specification.

**Comment by gavbaa** [comment]
What's wrong with a Pongo-equivalent of the Django-suggested solution?

```
@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)
```

We have an equivalent for our apps:

```
func FilterGetValueByKey(in *pongo2.Value, param *pongo2.Value) (*pongo2.Value, *pongo2.Error) {
        m := param.Interface().(map[string]string)
        return pongo2.AsValue(m[in.String()]), nil
}
pongo2.RegisterFilter("key", FilterGetValueByKey)
```

This is pretty easy to add to your app, right?  There's a separate repository, https://github.com/flosch/pongo2-addons , which you could submit a function like this to as a pull request and see if it gets accepted there.  That's up to @flosch , either here or there.

**Comment by shashankmehra** [comment]
There is nothing wrong with it, in the sense that you can always extend the template engine using your own custom filters. But this just seems like a functionality that should work out of the box, as most template engines do. It seems rather arbitrary that a filter like `phone2numeric` is a built-in filter but there is no built-in way to get children of an object dynamically.

The solution you provided works for a map[string]string object but most of the time we end up with a map[string]interface{}. I am working on a filter for that and I would be happy to send a PR to this repo or the addon repo, as you guys decide.

**Comment by Ashtonian** [comment]
just wanted to point out its not in the standard django template language: https://stackoverflow.com/questions/8000022/django-template-how-to-look-up-a-dictionary-value-with-a-variable

**Comment by flosch** [comment]
You can now use variable subscript: `mymap[myKeyVar]` or `mymap["myKey"]`.
