### ISSUE TITLE
How to access array at index by variable ?

### ISSUE THREAD

**Issue by cxxclean** [flosch/pongo2#164]
I have array A and array B:

        'A': ["small", "medium", "large", "verylarge"]
        'B': [100, 200, 300, 400, 500, 600]

	
now I want to print like this:

        small=100
        medium=200
        large=300
        verylarge=400
	
	
and I try the template below:

	{% for a in A %}	
		a={{B.{{forloop.Counter}}}}
	{% endfor %}
	
but there is error messege "This token is not allowed within a variable name.", I read the .tpl file under <pongo2\template_tests> but not found similar use, only found the way like "A.1" "B.3" "B.5".

How to write the template?

**Comment by gavbaa** [comment]
This is the same as #162 .  That's probably the best way to go, use a filter as a key lookup.

**Comment by cxxclean** [comment]
The filter seems powerful, I'll try it.
