### ISSUE TITLE
How to control whitespace in the template?

### ISSUE THREAD

**Issue by scy0208** [flosch/pongo2#168]
Jinjia uses {%- XXX -%} to control whitespace in the template cased by {%%},
How to achieve this in pongo?

**Comment by gavbaa** [comment]
Currently this project doesn't support that tag mode, because it's not part of the Django template standard that this project's primary goal is to maintain.

That having been said, I'm also interested in these Jinja tag extensions if you're offering a pull request! :)

**Comment by flosch** [comment]
This is added with v4.0.0.
