### ISSUE TITLE
multi-line tags

### ISSUE THREAD

**Issue by mmariani** [flosch/pongo2#169]
Hi,

what's your view on multi-line tags?
i.e.

```
{% with
   DEBUG=true
   ENABLE_THIS=false
   ENABLE_THAT=true
%}
```

possibly with \ or some such.
I see it's been refused in django but don't know the rationale.
My use case: configuration files for docker services.

thanks

**Comment by gavbaa** [comment]
The rationale is in this thread: https://groups.google.com/forum/#!topic/django-developers/wRKgnMIhl6g

While I see your sentiment, the rule stands: Django's templating language isn't for doing heavy logic, that should be in your view layer or filters or something else.  Also, PEP-8 doesn't apply to Go, so long lines aren't anathema per the language.

I say all this as someone who prefers Jinja, but Django's templating language is what it is.

**Comment by mmariani** [comment]
Thanks for the clarification. If I were rendering web content I would have a fancy view layer. I'll keep using pongo2 as it is, will possibly reconsider if it becomes too complex.
