### ISSUE TITLE
which filters and tags to ban to run client templates?

### ISSUE THREAD

**Issue by Ashtonian** [flosch/pongo2#170]
If we were using this for an email template which filters/tags should we ban to allow customers to use their own templates? Just trying to avoid malicious code.

So far I have banned the following tags: 
```go
pongo2.DefaultSet.BanTag("include")
pongo2.DefaultSet.BanTag("extends")
pongo2.DefaultSet.BanTag("ssi")
```

**Comment by RO-29** [comment]
FYI we have these tags banned for production client usage 

```
"block",
	"ifequal",
	"ifnotequal",
	"import",
	"include",
	"lorem",
	"macro",
	"ssi",
	"widthratio"
```
