### ISSUE TITLE
Can you use the Replace function as a filter?

### ISSUE THREAD

**Issue by marcuxyz** [flosch/pongo2#171]
Is it possible to use the strings.Replace function as a filter?

Ex: 
{{ variable | replace "cat", "dog", "-1" }}

Thanks guys

**Comment by gavbaa** [comment]
You're going to need to use a customer filter for that.  While not an exact example, you can see a pretty similar one here, as well as how to register a custom filter:

https://github.com/flosch/pongo2-addons/blob/master/filters.go#L52
