### ISSUE TITLE
registerTag

### ISSUE THREAD

**Issue by TheMangoTrain** [flosch/pongo2#172]
I have Pongo2 working, with multiple templates such as "Home", "Event", "Location", "User", etc. Each template uses a global header and footer, using extends, like so:

`{% extends "header.tmpl" %}`

`{% extends "footer.tmpl" %}`

I would like to run some Go func's and have the output appear in the header or footer. Note: my end goal is simply to have a "User" div at the top of every page, with signin/signout links, photo and alerts. I have an authentication system in place, integrated with my API.

So, assuming a basic existing Go func along the lines of:

```
func myStatus(w http.ResponseWriter, r *http.Request) {
    w.Write([]byte("User status is true"))
}
```
How can I use this func as a tag in my Pongo2 templates, like my header?

I have not yet successfully been able to get *any* custom Pongo2 tag to work. I have read the Pongo2 tags tutorial [here](https://www.florian-schlachter.de/post/pongo2/), and it seems pretty complex to do what I need. Do I really need to define a separate parser function and an executioning function? Is there not a way to simply inject my pre-existing generic Go func's into a Pongo2 template? Is there an alternate method to do what I need, perhaps not with Pongo2? Anyways I've also browsed whatever public code with "registerTag" I can find and looked at Django's documentation, to no avail.

**Comment by flosch** [comment]
Closing due to issue age. If this problem persists, please answer/re-open again.
