### ISSUE TITLE
Could you please upgrade releases?

### ISSUE THREAD

**Issue by kataras** [flosch/pongo2#175]
Hello @flosch , [dep](https://github.com/golang/dep) doesn't care about the package's vendor package so when users try to `dep init` and install the [iris web framework](https://github.com/kataras/iris) as third-party package of their own applications it downloads the `flosch/pongo2 version 3` which is very old and has different API than the `master/dev` version. 

Look here: https://github.com/kataras/iris/issues/1143#issuecomment-472035292

**Comment by robvdl** [comment]
It looks like tagging stopped 3 years ago, agreed, that is not cool for those of us that follow dependencies  via semver.

**Comment by flosch** [comment]
Fixed with release 4.0.0.
