### ISSUE TITLE
All links under https://florian-schlachter.de/ are broken

### ISSUE THREAD

**Issue by charlax** [flosch/pongo2#180]
Hey - all your links under https://florian-schlachter.de/ are broken and the homepage is empty.

All blog posts links are broken, e.g. https://florian-schlachter.de/post/pongo2-v3/

**Comment by flosch** [comment]
Yes, will fix that. My website's server is currently down.

**Comment by fearofcode** [comment]
Any updates on this?

**Comment by jordan0420** [comment]
Would be willing to help move + translate info / posts to github.io or project readme files.

**Comment by flosch** [comment]
Unfortunately not yet. I removed the broken links.
