### ISSUE TITLE
Expected error but receives template with invalid value

### ISSUE THREAD

**Issue by RO-29** [flosch/pongo2#181]
Hey, 
Ran into this unexpected output, can you suggest me whats the best way to handle this?

**Template**
```
 <html><body><p>{% templatetag openbrace %} {{ params }} {% templatetag closebrace %}</p></body></html>
```

**Context**
```
"params":{
    	"randomKey": RandomValue,
        "Random Nested json": 
            {
                "name": "Test 1",
                "price": Random data,
                "url": "google.com"
            }
    }
```

**Expected Output**

`Some error`

**Actual Output**
```
<html>
    <body>
        <p>{ 
            <map[string]interface {} Value> }
            </p>
        </body>
    </html>
```

**Comment by gavbaa** [comment]
Why would you expect to receive an error here?

Per the Django template tag documentation: https://docs.djangoproject.com/en/2.0/ref/templates/builtins/#templatetag , you're just asking it to print a literal curly brace {, followed by printing the contents of the params variable, followed by another literal curly brace } .  {{ params }} is rendering exactly how Go would render a map.  {% templatetag %} isn't for triggering non-execution behaviors in templates, it's just for printing literals.  If you want non-execution behaviors, you would use {% verbatim %}, as described here: https://docs.djangoproject.com/en/2.0/ref/templates/builtins/#verbatim

I ran your example through Django to verify:

View:
```
def index(request):
    template = loader.get_template('test1/index2.html')
    context = {
        "params": {
            "randomKey": 111,
            "Random Nested json": {
                "name": "Test 1",
                "price": 333,
                "url": "google.com"
            }
        }
    }
    return HttpResponse(template.render(context, request))
```

Template:
```
 <html><body><p>{% templatetag openbrace %} {{ params }} {% templatetag closebrace %}</p></body></html>
```

Output:
```{ {'randomKey': 111, 'Random Nested json': {'name': 'Test 1', 'price': 333, 'url': 'google.com'}} }```

I propose closing this as invalid, unless you have a case that actually triggers a broken behavior.

**Comment by RO-29** [comment]
@gavbaa OK maybe not an error but it should still return some "user-friendly" output like the one that was shared above

`<map[string]interface {} Value>` does not look very nice but maybe this is a "go" vs "Django" behaviour?

**Comment by gavbaa** [comment]
That's just the difference between how Go prints maps vs. how Python prints dictionaries.  Neither case is one you should be relying on, as that behavior is based on their various Stringers, and can change over time.  If you want to print a map, using a |json filter would be the most appropriate way to get a reasonable output.

**Comment by RO-29** [comment]
Ok thanks for explaining, sounds good to me 👍
