### ISSUE TITLE
how to do a dynamic include

### ISSUE THREAD

**Issue by marcelloh** [flosch/pongo2#184]
In my pongo2.Context I have configured what menu has to be shown

in my template I want to do something like this:
 {% include menu '/menu.html' %}
but I don't seem to find how this is done.
(in twig it is done via menu ~  '/menu.html')

**Comment by flosch** [comment]
Not sure I understand you correctly, you can use an expression in the include tag to dynamically construct your include statement. If this problem persists, feel free to answer again.
