### ISSUE TITLE
Does it possible to get current http.Request object in a template?

### ISSUE THREAD

**Issue by cartonlab** [flosch/pongo2#186]
Hi!

Does it possible to get current http.Request object in a template?

Thanks.

**Comment by gavbaa** [comment]
Just set the http.Request parameter being passed into your view into the Context:

```
func Func1(w http.ResponseWriter, r *http.Request) {
	ctx := pongo2.Context{
		"request": r,
	}
	tpl, _ := app.TemplateSet.FromCache("template.html")
	tpl.ExecuteWriter(ctx, rw)
}
```

**Comment by cartonlab** [comment]
Thanks!

How can I get assess to the http.Request from a custom defined filter?

**Comment by gavbaa** [comment]
You can pass the request to the filter as a param, and then pluck it out via Interface() on the pongo2.Value.

Unfortunately, as it currently stands, filters don't have a context or other unique identifier that you can reference to control behavior external from the function on a per-request basis.  There's a good argument for filter having access to the Context that could be configured on a per-Execute basis, maybe something like Django does with context processors?  Could turn into an interesting feature request.

**Comment by cartonlab** [comment]
Got it. Thanks a lot!
Wish you could manage it!
