### ISSUE TITLE
Tag 'from' not found (or beginning tag not provided)

### ISSUE THREAD

**Issue by mitjafelicijan** [flosch/pongo2#189]
Im using `import from` in my templates and having problems with getting it to work. FE developers use nunjucks when they are doing their work and this is pushed later to golang pongo2.

Example is from http://jinja.pocoo.org/docs/2.10/templates/#import and is also tested with nunjucks.

So my questions are:
- Is this kind of importing even supported?
- Is there a different way to achieve the same functionality?
- If not supported; is this in a pipeline to be added?
- Or is there a huge flaw/error in my code?

**Output log**
```
[Error (where: parser) in templates/import.njk | Line 1 Col 4 near 'from'] Tag 'from' not found (or beginning tag not provided)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x501466]

goroutine 1 [running]:
github.com/flosch/pongo2.(*Template).newBufferAndExecute(0x0, 0xc420016810, 0x30, 0x0, 0x0)
        /home/m/go/src/github.com/flosch/pongo2/template.go:143 +0x26
github.com/flosch/pongo2.(*Template).Execute(0x0, 0xc420016810, 0xc420016810, 0x0, 0xc420016810, 0x0)
        /home/m/go/src/github.com/flosch/pongo2/template.go:187 +0x39
main.main()
        /home/m/Dropbox/projects/backpack-apps/backpack-utilities/nunjucks-testing/main.go:19 +0xf3
exit status 2
```

**templates/import-forms.njk**
```njk
{% macro input(name, value='', type='text') -%}
    <input type="{{ type }}" value="{{ value|e }}" name="{{ name }}">
{%- endmacro %}

{%- macro textarea(name, value='', rows=10, cols=40) -%}
    <textarea name="{{ name }}" rows="{{ rows }}" cols="{{ cols }}">{{ value|e }}</textarea>
{%- endmacro %}
```
**templates/import.njk**
```njk
{% from 'forms.njk' import input as input_field, textarea %}
<dl>
    <dt>Username</dt>
    <dd>{{ input_field('username') }}</dd>
    <dt>Password</dt>
    <dd>{{ input_field('password', type='password') }}</dd>
</dl>
<p>{{ textarea('comment') }}</p>
```

**main.go**
```go
package main

import (
	"fmt"

	"github.com/flosch/pongo2"
)

func main() {
	var renderedHTML string

	loadedTemplate, err := pongo2.FromFile("templates/import.njk")
	if err != nil {
		fmt.Println(err)
	}

	payloadCtx := pongo2.Context{}

	renderedHTML, err = loadedTemplate.Execute(payloadCtx)
	if err != nil {
		fmt.Println(err)
	}

	fmt.Println(renderedHTML)
}
```

**Comment by gavbaa** [comment]
Jinja's {% from tag is not supported in this library.  The import tag (with "as" modifier) is supported, you can see an example of it here: https://github.com/flosch/pongo2/blob/master/template_tests/macro.tpl#L23

Since "import" is functionality beyond what  Django offers, but @flosch has already committed to supporting the very-closely related Jinja-specific import syntax, this is probably a reasonable additional tag to support from the POV of this library IMO.
