### ISSUE TITLE
Is there a filter for array returning the element at specified index?

### ISSUE THREAD

**Issue by shawnye** [flosch/pongo2#190]
The filer named "index" for example:
{{ array | index: 3 }}

It seems that django is not supported originally, 
Any suggestion ? thank you!

custom python filter: 
<pre>
@register.filter
def index(l, i):
 try:
  return l[i]
 except:
  return None
</pre>

**Comment by grt1st** [comment]
Try it:
```
func init() {
	pongo2.RegisterFilter("index", filterIndex)
}
func filterIndex(in *pongo2.Value, param *pongo2.Value) (*pongo2.Value, *pongo2.Error) {
	index := param.Integer()
	return pongo2.AsValue(in.Index(index)), nil
}
```

Learn more at: [https://github.com/flosch/pongo2/blob/9d978217a2f84fab35dd17731da1e1c23be32d14/filters_builtin.go](https://github.com/flosch/pongo2/blob/9d978217a2f84fab35dd17731da1e1c23be32d14/filters_builtin.go)
[https://github.com/flosch/pongo2/blob/9d978217a2f84fab35dd17731da1e1c23be32d14/value.go](https://github.com/flosch/pongo2/blob/9d978217a2f84fab35dd17731da1e1c23be32d14/value.go)

Also, a simple way:

`{{ array.index }}`

By the way, any filter needed? I'd be like to contribute some. @flosch

**Comment by MayukhSobo** [comment]
Try this

```go
pongo2.RegisterFilter("getField", func(in *pongo2.Value, param *pongo2.Value) (*pongo2.Value, *pongo2.Error) {
		obj := (*in).Interface().(Admins)
		attrb := param.String()
		return pongo2.AsValue(reflect.ValueOf(obj).FieldByName(attrb)), nil
	})
```

**Comment by flosch** [comment]
You can use `array[0]` now.
