### ISSUE TITLE
Using Pongo2 with Packr

### ISSUE THREAD

**Issue by botherder** [flosch/pongo2#192]
I'm trying to use pongo2 with packr in order to bundle everything in one binary. it seems to be working ok by using something like `pongo.Must(pongo.FromString(templatesBox.String("index.html")))`
The problem begins when the template file extends another template file which pongo seems to try to load using FromFile.

Any suggestions on how I can manage this?

**Comment by not-omer** [comment]
Did you ever find a solution to this issue?

**Comment by botherder** [comment]
Nope. I just have not been using templates unfortunately and only using single files.

**Comment by not-omer** [comment]
Gotcha. Thanks anyway!

**Comment by 12foo** [comment]
Hi. Just had to do this for a thing, so I'll leave an example solution here. Basically you can do this using a TemplateSet with a custom TemplateLoader.

```go

import (
	"bytes"
	"github.com/flosch/pongo2"
	"github.com/gobuffalo/packr"
	"path"
)

type packrBoxLoader struct {
	box *packr.Box
}

func (l packrBoxLoader) Abs(base, name string) string {
	// this is the bit that finds the correct import path
	p := path.Join(path.Dir(base), name)
	return p
}

func (l packrBoxLoader) Get(path string) (io.Reader, error) {
	b, err := l.box.MustBytes(path)
	if err != nil {
		return nil, err
	}
	return bytes.NewReader(b), nil
}

// during setup / server start
tplbox := packr.NewBox("templates")
tplset := pongo2.NewSet("templates", packrBoxLoader{tplbox})
tplset.Debug = true // set to true to recompile templates every time

// later in your handler...
tpl, err := tplset.FromCache("index.html")
tpl.ExecuteWriter(context, writer)

```

Hope this helps.

**Comment by botherder** [comment]
Thanks @12foo!
