### ISSUE TITLE
Q: How do I access nth element of a member slice?

### ISSUE THREAD

**Issue by dalu** [flosch/pongo2#198]
I have something like this:
```
<div><a href="/threads/{{ thread.ID.String }}">{{ thread.Posts[0].Title }}</a></div>
```
this panics with
```
[Error (where: lexer) in view-forum.html.twig | Line 26 Col 87] Unknown character: '[' (91)
```

**Comment by dalu** [comment]
I solved it by
```
                        <div><a href="/threads/{{ thread.ID.String }}">{{ thread.Posts.0.Title }}</a></div>
```
However...
it doesn't help with a problem like this
```
                            <div class="text-md-right">{{ thread.Posts[(thread.Posts|length)-1].Profile.Name }}</div>
                            <div class="small text-md-right">{{ thread.Posts[(thread.Posts|length)-1].UpdatedAt|date }}</div>
                        </div>

```

**Comment by dalu** [comment]
This doesn't work
```
                            {% with ln=((thread.Posts|length)-1) %}
                                {{ ln }}
                                {% with post=thread.Posts.ln %}
                                    {{ post }}
                            <div class="text-md-right">{{ post.Profile.Name }}</div>
                            <div class="small text-md-right">{{ post.UpdatedAt|date:"d.m.y" }}</div>
                                {% endwith %}
                            {% endwith %}
```

**Comment by dalu** [comment]
When you build on abandoned software, I'm so tired of this open source crap.
If you don't mean to maintain it - don't publish it. Simple.

**Comment by gavbaa** [comment]
What you want to do is specifically not supported by the Django template language in that way, as part of the language's definition.  This project is an attempt to be a clone of Django's templating language, so it's no surprise that it's working exactly as it says on the tin.

Some examples: https://stackoverflow.com/questions/4651172/reference-list-item-by-index-within-django-template/29664945

See #190 for mechanisms on how to do this with filters in Pongo, which is the Django approved way.

**Comment by dalu** [comment]
Yeah but you can't do
Struct.Slice[len(Slice.SubSlice)-1]
https://docs.djangoproject.com/en/dev/ref/templates/api/#variables-and-lookups

> List-index lookup. Example: foo[bar]

not implemented in pongo2

list-index lookup is essential functionality, even Twig has it.
It's also in Go. Natively.
Writing a filter is doctoring on the symptoms instead of fixing the disease.

Slice[expr] should be possible

**Comment by gavbaa** [comment]
Unfortunately, you're mis-reading that.  It will do an explicit lookup, but won't do a variable lookup.

Django example:
```
    t = Template("The first stooge in the list is {{ stooges[bar] }}.")
    c = Context({"bar": 1, "stooges": ["Larry", "Curly", "Moe"]})
    print(t.render(c))
```

Output error: ```TemplateSyntaxError at /
Could not parse the remainder: '[bar]' from 'stooges[bar]'```

That's intentional by the Django developers.  [] is not a syntax allowed in Django templates.  If you would like to change Django's template behavior, you should take it up with the Django developers in their issue tracker, here: https://code.djangoproject.com/

However, it's been reported and noted as Not a Bug by them before, see here: https://code.djangoproject.com/ticket/24284

That's their choice, and this project's goal is to stick faithfully to Django's template decisions as much as possible.

**Comment by dalu** [comment]
Who cares about Django?
Who made them the authority on what is right or wrong?
This is a real world problem, not a freaking academic construct.

And btw pongo-addons and v3 don't work because it imports the master version and v3 doesn't have the OrigError field.
Non-considerations like these is what I'm sick and tired of.
Also the brick wall of ignorance. "But Django said it isn't needed" Fuck Django. Put that Nigga in chains and hang him by the balls.
If I wanted to use Django I would.

Don Quichote - out
