### ISSUE TITLE
Get value by key from map

### ISSUE THREAD

**Issue by vgarvardt** [flosch/pongo2#20]
I'm passing `map[string]string` to pongo2 context and want to verify if a key is set: 

```
<div class="form-group {% if errors[`Path`] %}has-error{%endif%}">
```

This gives panic:  `2014/07/26 21:56:39 PANIC: [Lexer Error in ./templates/grayscale/form.html (Line 70 Col 38)]: Unknown character: '[' (91)`

Also tried `errors.Path` - does not panic, but does not check if the key is set. After key is checked and exists I want to print its value (does not work either).

Is it possible to do this with current pongo2 implementation or I need to implement filter, something like this: `{{ errors|map_key:"Path" }}`?

**Comment by spaceblock** [comment]
not work, where stupid example?
