### ISSUE TITLE
set array in template

### ISSUE THREAD

**Issue by kopachevsky** [flosch/pongo2#208]
Seems to be this statement not works, any plans to support it?

`{% set environments = ['dev', 'qa', 'prod'] %}`

**Comment by chhetripradeep** [comment]
@kopachevsky I am seeing the same issue - were you able to find a workaround ?

**Comment by kopachevsky** [comment]
@chhetripradeep no, just abandon use this framework

**Comment by chhetripradeep** [comment]
Thank you for the response. Did you end up using any open source library ? I am looking for one too.

**Comment by kopachevsky** [comment]
native go templating works okay

**Comment by kopachevsky** [comment]
closing issue, noone reacting and I dont want issue to hang than in my list

**Comment by ali-sendinblue** [comment]
For future users who come for a solution, now arrays should be defined like this:
```
{% set environments = array('dev', 'qa', 'prod') %}
```
