### ISSUE TITLE
tags_for.go: reference to the NodeTag

### ISSUE THREAD

**Issue by dgofman** [flosch/pongo2#212]
In the Django Form class implementation of "for in" may return two different collections.
I first node name starts from "field" the result will be for an array of fields otherwise to the field dictionary.

Initially, implementation was:
```
ctx["form"] = func(ctx *pongo2.ExecutionContext) interface{} {
	isLoop := ctx.Private["forloop"]
	if isLoop != nil {
			return f.list
	}
	return f.dict
}
```

However, if for loop defined for other objects I am getting cast exception. To handle this problem I need to know the child "key" name.

**Comment by dgofman** [comment]
My workaround related to changes in tags_for.go:

type tagForLoopInformation struct {
	Counter     int
	Counter0    int
	Revcounter  int
	Revcounter0 int
	First       bool
	Last        bool
	Parentloop  *tagForLoopInformation
	**TagNode 	*tagForNode**
}

Now I initializing struct as:
```
// Create loop struct
	loopInfo := &tagForLoopInformation{
		First: true,
		TagNode: node,
	}
```

In that case, I can return List  of Field ONLY when the key is "field"
```
ctx["form"] = func(ctx *pongo2.ExecutionContext) interface{} {
	isLoop := ctx.Private["forloop"]
	if isLoop != nil {
		el := reflect.ValueOf(isLoop).Elem()
		tag := el.FieldByName("TagNode").Elem()
		key := tag.FieldByName("key").String()
		if key == "field" {
			return f.list
		}
	}
	return f.dict
}
```

**Comment by dgofman** [comment]
PR: https://github.com/flosch/pongo2/pull/213

**Comment by flosch** [comment]
Do you have any link to the Django documentation and example template on what you want to accomplish?
