### ISSUE TITLE
need help for pongo2's syntax

### ISSUE THREAD

**Issue by dayuoba** [flosch/pongo2#218]
i've searched and watched the docs, but i don't know how to just `ignore` some blocks in template.  

e.g.

temp:
```text
hello {{name}}

below is some block contains some syntax conflict with pongo2's syntax
i want to just skip this blocks

{% skip %}

{{#success build.status}}
   do something
{{else}}
  do something else
{{/success}}

{% endskip %}

here is other text won't be ignored
hi {{ pongo }}

````

i want to konw if we have some syntax like `{% comment %}` but it's behavior is just skip/jump some block

any helps is welcome, thx!

**Comment by gavbaa** [comment]
According to: https://github.com/flosch/pongo2/commit/c3edbede595c11c14431eff6e0331e0972bca1ec , both comment formats should provide exactly this functionality with the current version.  You can look at the tests in there to see more.

**Comment by dayuoba** [comment]
thank you for response, but what i mean is that i need the `text` between some tag like `skip` may just stay there, as the `comment` tag will rm all contents between them.

**Comment by gavbaa** [comment]
You're looking for {% verbatim %} then.  You can see examples here: https://github.com/flosch/pongo2/blob/67f4ff8560dfa2b00920118f228c0a2f68760631/template_tests/verbatim.tpl

**Comment by dayuoba** [comment]
oh! that's cool ! thank you for time. : )
