### ISSUE TITLE
Flag for absolute paths instead of relative. (Jinja2 compatibility)

### ISSUE THREAD

**Issue by virtualsnow** [flosch/pongo2#225]
The only thing preventing _basic_ Jinja2 templates from being compatible with Pongo2's templating engine is the usage of relative links in `{{ include }}` or `{{ extends }}` etc., instead of absolute.

This is unfortunate since it would be very nice to have the huge number of existing simple templates from Jinja2 "just work". For example, porting Pelican to Go while having all the themes be drop-in replacements would be quite simple using Pongo2 if it considered references to be absolute.  Users of Pongo2 may find absolute links useful even without consideration of Jinja2, since it is more exact, and therefore less prone to bugs/edge cases.

Unfortunately, it would be a breaking change, so I suggest the loaders carry a flag. Or, ideally, the templates carry an optional declaration that switches operation to absolute (but doesn't make Jinja2 angry).

**Comment by gavbaa** [comment]
You could probably do this without too much trouble by implementing the template loader interface.  Here's an example of a simple one: https://github.com/sharpner/pobin/blob/master/loader.go

That having been said, Pongo2 appears to already support absolute paths in the built-in template loader: https://github.com/flosch/pongo2/blob/master/template_loader.go#L81 .
