### ISSUE TITLE
Link to Django 1.7 reference broken

### ISSUE THREAD

**Issue by falzm** [flosch/pongo2#226]
The link to Django version compatibility 1.7 in the README's *Development status* section is broken, it looks like this version is not supported anymore: https://docs.djangoproject.com/en/1.7/ref/templates/builtins/

I suggest to either include a reference of actually implemented filters in your project's documentation, or ensure support for Django 1.8 or higher so you can link to their documentation.

**Comment by netroby** [comment]
Shall we add more document link or PDF document ?
https://django.readthedocs.io/en/1.7.x/topics/templates.html

[django-doc.pdf](https://github.com/flosch/pongo2/files/5213752/django-doc.pdf)


@flosch

**Comment by flosch** [comment]
Fixed, thanks.
