### ISSUE TITLE
Proposal: Please tag a new release and start using Semantic Versioning

### ISSUE THREAD

**Issue by KateGo520** [flosch/pongo2#239]
I found that this project already [supports Go modules](https://github.com/flosch/pongo2/blob/master/go.mod). But sadly, the [tags](https://github.com/flosch/pongo2/tags) doesn't follow [Semantic Versioning](https://semver.org), which means that all tags of this project will be ignored by Go modules and replaced by pseudo-versions, go get acts weirdly when tags are not in that form. It would be great to have the tagged release be named in the format vX.X.X format so that go mod can read it. 
```
	github.com/flosch/pongo2 upgrade v0.0.0-20200529170236-5abacdfa4915
```
Else the mod file shows something like `github.com/flosch/pongo2 upgrade v0.0.0-20200529170236-5abacdfa4915` which is not very readable and difficult to upgrade. It’s hard to verify which version is in use. This is not conducive to version control

So, I propose this project to follow Semantic Versioning in future versions. For example, `v1.0.1`, `v2.0.0`, `v3.1.0-alpha`, `v3.1.0-beta.2`etc.

Issues：[#238](https://github.com/flosch/pongo2/issues/238), [#233](https://github.com/flosch/pongo2/issues/233)

**Comment by KateGo520** [comment]
@flosch  @pierrre  Could you help me review this issue? Thx :p

**Comment by kataras** [comment]
@KateGo520 I am also asking for this, read the discussion at: https://github.com/flosch/pongo2/pull/236#issuecomment-668950566. Hope they will get back to us or at least let me do the work.

**Comment by KateGo520** [comment]
@kataras  Thank you for your reply! Maybe the author can help.
@flosch  Could you help me review this issue? Thx :p

**Comment by flosch** [comment]
Fixed with https://github.com/flosch/pongo2/releases/tag/v4.0.0
