### ISSUE TITLE
Request For Comment: include pongo2gin inside the pong2 project.

### ISSUE THREAD

**Issue by netroby** [flosch/pongo2#245]
Hello, Dear author and community memebers:

I saw there be many forks of pongo2gin, a gin framework middleware with pongo2, 
Can we put pongo2gin  as a part of pongo2 project?

Or there not enough hands on make the pongo2gin update match with pongo2 project.

**Comment by flosch** [comment]
Hi,
thanks for your feedback!

I don't think that'd be a good idea as pongo2 is not limited to web frameworks only. Adapters should reside outside pongo2 which only focuses on providing a template engine.
