### ISSUE TITLE
how to access an attribute inside filter chain

### ISSUE THREAD

**Issue by sseide** [flosch/pongo2#278]
Hello,

i try to figure out how i can access an object attribute within the filter chain.
Lets say I have the following list of items:
```
mylist = [
  {"Key":"a-key-1", "Value":"my-value-1"},
  {"Key": "another-key", "Value": "something-else"}
]
```
Now how do i access the Key of the first value? Something along the following (non-working) example
```
set x = mylist | first | .Key
set y = mylist | first | .Value | cut:"-"
```
and "x" having "a-key-1" and "y" holding "myvalue1".

Within Jinja2 the "attr()" filter exists to access attributes: `mylist | first | attr("Key")`.
How do i solve this with pongo2?

Thanks

**Comment by flosch** [comment]
You could probably write a custom filter to access the desired key. There's none built-in to accomplish this, but I can think about having one integrated.
