### ISSUE TITLE
Remove repositories with stolen source code and give credit to their original authors

### ISSUE THREAD

**Issue by dieselburner** [flosch/pongo2#290]
Following repositories, which are mentioned on [Pongo2 web page](https://www.schlachter.tech/solutions/pongo2-template-engine) and [README](https://github.com/flosch/pongo2/blob/master/README.md), were stolen by removing the names of the original authors and literally squashing entire commit history into one commit:

- https://github.com/stnc/pongo2echo
  - squash commit: [5f9e1d35a56ab243af0efabd7b09e179e65268a3](https://github.com/stnc/pongo2echo/commit/5f9e1d35a56ab243af0efabd7b09e179e65268a3)
  -  original repository: https://github.com/siredwin/pongorenderer

- https://github.com/stnc/pongo2gin
  - squash commit: [8441d5da6a6cc33f43479532bd69a0a4ec6c1a51](https://github.com/stnc/pongo2gin/commit/8441d5da6a6cc33f43479532bd69a0a4ec6c1a51) with extra changes like renaming structs or variable names
  -  original repository: https://github.com/robvdl/pongo2gin, deleted (or made private), but function signatures are documented [here](https://pkg.go.dev/github.com/robvdl/pongo2gin). There're plenty of forks of this original repository that maintains the original history.
    [update] @robvdl [informed](https://github.com/flosch/pongo2/issues/290#issuecomment-1047254307) his repository moved to a new location: https://gitlab.com/go-box/pongo2gin

**Comment by dieselburner** [comment]
@flosch I would like to ask you to reflect these changes on the project home page as well.

**Comment by dieselburner** [comment]
@robvdl I (and others) would appreciate if you could bring mentioned repository back. Thanks for your efforts.

**Comment by robvdl** [comment]
Hi @dieselburner I don't quite get what happened, so are you saying https://github.com/stnc/pongo2gin has stolen my code at https://gitlab.com/go-box/pongo2gin squashed the git history, thrown an example in and claimed it as his own?

**Comment by dieselburner** [comment]
> Hi @dieselburner I don't quite get what happened, so are you saying https://github.com/stnc/pongo2gin has stolen my code at https://gitlab.com/go-box/pongo2gin squashed the git history, thrown an example in and claimed it as his own?

Correct. And this MR is my sweet revenge.

> I moved the code to Gitlab a while ago, and into a group so me and a mate can both maintain it, and others who want to join off course. The go-box group is the official group for our Go projects. You can see the original git history there.

Thanks for the info. Yes, now I see it.

**Comment by dieselburner** [comment]
FYI: pseudo-author confirmed of what happened and removed one of the repositories in this change: https://github.com/gin-gonic/contrib/pull/202#issuecomment-1056916929

**Comment by robvdl** [comment]
Cool, I'm OK with adding my repo again later. It needs some work anyway updating and looking through pull requests and testing again with the latests version. I can add it again later.
