### ISSUE TITLE
[Question] Serving static files  built with webpacks

### ISSUE THREAD

**Issue by Swechhya** [flosch/pongo2#298]
Is there any tag to support static files that are generated using webpack.

For example:
I have a CSS file navbar.css but after webpack build the file created is navbar.[<hashvalue>].css
Is there any tag to substitute the value with the hash value?

**Comment by iredmail** [comment]
Is this a pongo2 issue? I don't think so. :(

**Comment by Swechhya** [comment]
So do we need to write a custom tag for this?

**Comment by flosch** [comment]
This isn't anything which should be of pongo2's responsibility.
