### ISSUE TITLE
Can nested var supported?

### ISSUE THREAD

**Issue by iyaozhen** [flosch/pongo2#304]
Demo

```Go
context := map[string]any{
    "map1":  map[string]string{"key1": "value1", "key2": "value2"},
    "var2":  "key1",
}
```

`{{map1.{{var2}}}}` fail, error = [Error (where: parser) in <string> | Line 1 Col 8 near '{{'] This token is not allowed within a variable name

`{{map1.var2}}` got = , want value1

**Comment by flosch** [comment]
Try `map1[var2]`.

**Comment by flosch** [comment]
Try ‘map1[var2]’, this should work.

Yao Zhen ***@***.***> schrieb am Fr. 8. Juli 2022 um 14:26:
