### ISSUE TITLE
How to use the template engine?

### ISSUE THREAD

**Issue by SharkFourSix** [flosch/pongo2#306]
I'm having difficulties using this engine because there's zero documentation.

I'm only getting by because it's similar to Twig. The issues I'm having are

1. Multiple level inheritance doesn't seem to work properly.
2. Cannot extend a block while retaining parent block content. In Twig,  you can use ```{{ parent() }}``` to render parent block

**Comment by flosch** [comment]
Documentation is part of #36. Feel free to elaborate on your first point to evaluate whether there's a bug or not. Thanks.
