### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by benharvie** [flosch/pongo2#325]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@cokebeer) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by flosch** [comment]
Done.

**Comment by cokeBeer** [comment]
Better have a look at how other famous template engines warn even an information leak: http://masterminds.github.io/sprig/os.html. In a word, you have no idea of what a potential security issue may harm at all.
