### ISSUE TITLE
date filter does not work as expected

### ISSUE THREAD

**Issue by Peter2121** [flosch/pongo2#326]
Maybe, I don't use it correctly, but I cannot find any example.
Trying to render:
`{{ time.Now()|date }}`
I get the following error:
`filter input argument must be of type 'time.Time'`

**Comment by flosch** [comment]
You need to pass a time object to your template with a context and then you can use the `date` filter with it. See the [caveats](https://github.com/flosch/pongo2#filters) in the README regarding the format as it adheres to the Go time format.

**Comment by Peter2121** [comment]
@flosch 
Sorry, but _caveats_ section in the README concerns the _format_ to use. For me, `time.Now()` **is** a time _object_ needed by the `date` filter. So I still don't see any evident reason why `{{ time.Now()|date }}` does not work. Please, put a link to an example explaining how to use `time.Now()` with `time` and `date` filters.

**Comment by flosch** [comment]
Can you please show the context you're passing to your template? What is "time" in your template? There's no built-in symbol called "time". You could easily pass the current time (such as the result of `time.Now()` to a variable `myTime` in your context and pass that variable to the `date` filter.

**Comment by Peter2121** [comment]
> There's no built-in symbol called "time".

OK, so _this_ is a problem. Thank you.
In such case it seems to be impossible as I have no context, I render a simple pongo2 template with [p2cli](https://github.com/wrouesnel/p2cli) :
```
% cat test.j2
rendertime: {{ time.Now()|date }}
% p2 --template=test.j2
ERRO[0000] Failed to execute template: [Error (where: filter:date) | Line 1 Col 27 near 'date'] filter input argument must be of type 'time.Time'  output_path= source="main.go:458" template_path=
ERRO[0000] Errors encountered during template processing  source="main.go:465"
```

So, finally I used the tag `now` to produce the timestamp:

```
% cat test2.j2
rendertime: {% now "02-Jan-2006 15:04:05" %}
% p2 --template=test2.j2
rendertime: 01-Feb-2023 16:18:05
```
