### ISSUE TITLE
Bug: random order for `for` loop.

### ISSUE THREAD

**Issue by leandergangso** [flosch/pongo2#337]
Data of `Test` in go file
```go
Test := map[string]string{"key1": "value1", "key2": "value2", "key3": "value3"}
```

teamplte.html
```django
{% for k, v in Test %}
<p>{{k}}: {{v}}</p>
{% endfor %}
```

Result in HTML
```html
<p>key2: value2</p>
<p>key3: value3</p>
<p>key1: value1</p>
```

Bug: the `key1` should be placed first, but is the last element.
This does not always happen, but at random times the order "toggles" between the result above, and the "expected" result.

This seems to be a problem mainly when looping over a `map`. Using a struct
does not have this problem.

Goal: I don't want to sort it based on the number, so using `sorted` dosen't work for me here, I need to render the output based on the order of the map input.

PS: i'm using fiber, along with this templating engine to render the html.

**Comment by gavbaa** [comment]
This is how Go works, iterating on maps is intentionally unstable.  See https://github.com/golang/go/issues/54500 for example.  It's reasonable for Pongo to treat this the same way Go does.

**Comment by iredmail** [comment]
Pongo has a builtin filter to sort keys.
FYI https://github.com/flosch/pongo2/blob/c84aecb5fa79a9c0feec284a7bf4f0536c6a6e99/template_tests/for.tpl#L11-L27
