### ISSUE TITLE
Base directory

### ISSUE THREAD

**Issue by ahall** [flosch/pongo2#41]
I usually have my templates in a separate directory e.g. structures something like:

```
templates/base.html
templates/user/index.html
```

In user.html I'd like to do something like:

```
{% extends "base.html" %}
```

Currently having to reference it like {% extends "../base.html" %}. I'd prefer if I could specify a template root and then reference it like a sandbox. It would also let me render "user/index" within the sandbox instead of specifying the full path. Does this make sense? Thanks for a great project, it's looking very useful.

**Comment by siredwin** [comment]
What was the solution to this? I am having same issue

**Comment by digitalcrab** [comment]
@siredwin it should be fixed now.
