### ISSUE TITLE
Add virtual filesystem with support for template inheritance

### ISSUE THREAD

**Issue by Unknwon** [flosch/pongo2#68]
Maybe provide an interface that allows custom implementation of how to retrieve files.

**Comment by happierall** [comment]
Ah, how i can use it?

**Comment by Unknwon** [comment]
@happierall I don't think it's working yet, we should wait until `v4` released.

**Comment by happierall** [comment]
```Bash
[GIN-debug] Listening and serving HTTP on :30012015/01/17 09:58:23 /Users/ruslan/Work/Go/bin
2015/01/17 09:58:23 stat /Users/ruslan/Work/Go/bin/templates: no such file or directory
```

**Comment by flosch** [comment]
@happierall development of virtual file systems is not finished yet.

**Comment by happierall** [comment]
is completed?

**Comment by flosch** [comment]
Not yet, I'm quite busy and couldn't afford enough time to work on this issue.

**Comment by thatguystone** [comment]
I, too, would love this feature. Have there been any updates about its future?

:+1:

**Comment by interlock** [comment]
Is this feature on a public branch? We could chip in to help get this in to v4 :smile:

**Comment by flosch** [comment]
I understand it's an important feature for you all and I will promise to release a next pongo2 release in the foreseeable future :)

**Comment by happierall** [comment]
Flosch, thank you.

**Comment by jonywtf** [comment]
+1
This is a very important feature!
I dream of binary serialization TemplateSet)

**Comment by interlock** [comment]
@flosch I'll put a bounty on this to complete it. Message me and we'll set it up.

**Comment by happierall** [comment]
@James S, You can use another solution with pongo2.
See: https://gist.github.com/happierall/090f6e2e85be63c25d09

ср, 29 июля 2015 г. в 6:15, James S <notifications@github.com>:

**Comment by interlock** [comment]
That won't work for us. We need to include from inside the templates. What will it take to complete the virtual file system? This library meets all our needs but this. We are willing to complete the exiting work if a branch is posted or pay to have the enhancement finished. There is a simple open PR that provides the interface to shim this in as well. Something has to move, what can we do to help?



—

**Comment by flosch** [comment]
I'm working on it and will release a first draft soon. If you want to help somehow financially, please consider donating to a charity organization. That would make me happy. Thanks!

**Comment by flosch** [comment]
You might want to check the branch pongo2/virtua-fs out. Please let me know if this fulfills your requirements. You simply have to implement the `TemplateLoader` interface and pass a instance of your own template loader to `NewSet()`.

**Comment by interlock** [comment]
Thank you so much @flosch Our team will organize a donation to a charity here in Canada. We will give this branch a whirl later today or early next week. A quick glance show that it does everything we need, so :+1: and thank you again.

**Comment by flosch** [comment]
It got merged into master.

**Comment by Unknwon** [comment]
Thanks @flosch !

**Comment by happierall** [comment]
Thanks!

чт, 3 сент. 2015 г. в 1:48, 无闻 <notifications@github.com>:

**Comment by andreimarcu** [comment]
Sorry to comment on an old issue, but do you have any idea of how to use this with go.rice?

**Comment by happierall** [comment]
Write middleware and render from string.

**Comment by Unknwon** [comment]
@andreimarcu I'm not sure what go.rice does but I think it will not be used in my use cases, and just like @happierall said you should simply write a middleware handler and use interface `TemplateLoader ` to maintain your template files from any possible source.

**Comment by happierall** [comment]
@andreimarcu <https://github.com/andreimarcu> like it
https://gist.github.com/happierall/1048e57932adbfe2dcbe

пн, 28 сент. 2015 г. в 17:00, 无闻 <notifications@github.com>:

**Comment by andreimarcu** [comment]
@Unknwon, @happierall Thank you! That's very helpful.

**Comment by diyan** [comment]
@flosch Big thanks for the TemplateLoader interface. 22499f94d3d56c7238591344a6902715d0b8fbbf works fine for me.

FYI. Here is my setup with labstack/echo renderer, pongo2 and go.rice:
https://gist.github.com/diyan/63f2169e6ccc85c869d7c5f19d7b211e

/cc @andreimarcu @happierall @Unknwon @interlock @jonywtf @thatguystone

**Comment by rverton** [comment]
For everyone coming here looking for a go1.6 embed version of the `pongo2.TemplateLoader`, have a look [here](https://github.com/rverton/webapp-base/blob/0d1b9ca35483cce5a8c6c7856c7ec6834502317f/renderer.go). I took the code from @diyan as an example an adjusted it, thanks!
