### ISSUE TITLE
How to assign values?

### ISSUE THREAD

**Issue by brongineers** [flosch/pongo2#74]
Is it possible to create and assign local variables inside template?

(something like standart text/template: {{ $x :=10 }}  )

And if not, I can use context object and it's fine, but how can I assign it to a new value? 
e.g. i need to add 2 to 10 and save it for later use
https://www.florian-schlachter.de/pongo2/?id=263970425

**Comment by flosch** [comment]
Please have a look here:
https://www.florian-schlachter.de/pongo2/?id=1594462451

Does this solve your issue?

**Comment by brongineers** [comment]
Yes, this is great! Thank you very much!
