### ISSUE TITLE
Compile at runtime

### ISSUE THREAD

**Issue by srikanthegdee** [flosch/pongo2#77]
What API can I use to compile the templates during runtime? Is it possible?

Thanks

**Comment by flosch** [comment]
Any template is compiled during runtime. You usually would call `FromFile()` (or a related function) on program startup which returns a (compiled) `Template` instance. This is the recommended way for peformance reasons. If you want to recompile on every HTTP request (or something like that), simply call [`FromFile`](http://godoc.org/github.com/flosch/pongo2#TemplateSet.FromFile) or any other function which creates a `Template` instance on-demand.

Does this answer your question?

**Comment by srikanthegdee** [comment]
Thanks a lot. This is exactly what I needed.

**Comment by flosch** [comment]
Please keep in mind that you shouldn't recompile a template on every HTTP request because this slows down your request handling significantly (each compile leads to a file read from disk).

You're welcome.

**Comment by srikanthegdee** [comment]
Thanks, I will keep in mind!
