### ISSUE TITLE
Nil error is not nill and yet is nil

### ISSUE THREAD

**Issue by mpnordland** [flosch/pongo2#80]
This has been frustrating me all night. I originally found this bug in the application I'm building, and then built a stripped down example that reproduces it in 10 lines.

    package main
    import "gopkg.in/flosch/pongo2.v2"
    import "fmt"
    func main() {
        err := fmt.Errorf("This is a test error")
        _, err = pongo2.FromFile("./test.html")
        if err != nil{
            fmt.Print(err)
        }
    }

The expected behavior is that fmt.Print will print out the error value. Instead it prints '<nil>'. Accessing methods on this results in a panic. Encountered on 64bit Archlinux using pongo2.v2 If you use a separate error value for for the from file, then everything works. Note that this assumes you have a valid template in `./test.html`.

**Comment by flosch** [comment]
This is already fixed in pongo2.v3: https://www.florian-schlachter.de/post/pongo2-v3/
Since it was an API change again, it resulted in v3.
