### ISSUE TITLE
request for example of passing JSON into Context without escaping quotes

### ISSUE THREAD

**Issue by tvmaly** [flosch/pongo2#81]
When I have something like 

	ctx := pongo2.Context{
			"title":      "Hello World",
			"id":         id,
			"json": jsonString,
	}

Inside the template, all the quotes in the jsonString appear as HTML escaped entities.   I am not exactly sure what I need to do to prevent the json from being escaped into HTML entities.  Could you provide an example?

**Comment by flosch** [comment]
pongo2 doesn't parse any JSON, you have to parse your JSON string on your own and pass the parsed JSON to the pongo2 context. For example:

```
import "encoding/json"

type Person struct {
    Name string
    Age int
}

func main() {
    jsonStr := `{"name": "jessy", "age": 29}`
    var p Person
    err := json.Unmarshal([]byte(jsonStr), &p)
    if err != nil {
        log.Fatal(err)
    }
    ctx := pongo2.Context{
        "person": p,
    }
}
```

You can access the fields in a pongo2 template like this: ```Hello {{ person.Name }}```

Does this answer your question?

**Comment by tvmaly** [comment]
Yes it does, thank you.
