### ISSUE TITLE
How can I fliter the time.Time with "date" ?

### ISSUE THREAD

**Issue by Michael2008S** [flosch/pongo2#83]
code like this:
```
<p>注册时间:{{guider.Created|date:"yyyy-mm-dd hh:mm:ss"}}</p>
```

html page show like this:
```
注册时间:yyyy-mm-dd hh:mm:ss
```
the  ``` |date:"yyyy-mm-dd hh:mm:ss"  ``` not work.
How can I fliter the time.Time with "date" ?

**Comment by flosch** [comment]
You might want read this: https://github.com/flosch/pongo2#filters

Does this answer your question? :-)

**Comment by Michael2008S** [comment]
Thx.
