### ISSUE TITLE
How do you check if time.Time isn't time.Time{}?

### ISSUE THREAD

**Issue by dalu** [flosch/pongo2#90]
I have a struct
```go
type Post struct {
// ...
Updated time.Time
}
```

When I do
```
{% if post.Updated %}
``` 
this evals to true since the field exists and an empty time.Time is time.Time{} aka 0 or Mon Jan 1 0001 00:00:00 UTC

So how do I check if it's set?

A workaround could probably be
```
{% if post.Updated.Year() > 1900 %}
```
but it's a workaround

**Comment by taezaz** [comment]
{% if !post.Updated.IsZero() %}

**Comment by dalu** [comment]
ah stupid me, thanks @taezaz

**Comment by pedromorgan** [comment]
Shoud that also  accom isNull() ??
