### ISSUE TITLE
Eat my newline

### ISSUE THREAD

**Issue by mickep76** [flosch/pongo2#94]
It would be great to have the same "eat my newline" as Jinja has "-%}" and "{%-".

This is very usefull when using Pongo for non-web development templating or if you're a neat freak.

**Input:**

```
hosts: [ "stinky", "grumpy", "whoops" ]
```

**Template:**

```
{% for host in hosts %}
{{ host }}
{% endfor %}
```

**Yields:**

```

stinky

grumpy

whoops

```

What would be nice:

**Template:**

```
{% for host in hosts -%}
{{ host }}
{% endfor -%}
```

**Yields:**

```
stinky
grumpy
whoops
```
##

**Comment by pedromorgan** [comment]
+1

**Comment by smithjm** [comment]
++ definitely would be helpful!

**Comment by flosch** [comment]
I agree, I'll put it on the TODO.

**Comment by mickep76** [comment]
Awesome!

**Comment by Mrhyuan** [comment]
+1 any news?

**Comment by flosch** [comment]
Not yet

**Comment by jgautheron** [comment]
Would be awesome indeed!
The same issue has been posted on the `django` project: https://code.djangoproject.com/ticket/2594

**Comment by odedlaz** [comment]
@flosch I'll be happy to do this. Can you give me some pointers on where to start?

**Comment by flosch** [comment]
Should be fixed
